In [2]:
import pandas as pd
print("imported")

imported

In [4]:
student_data = {"name": ['claude', 'jack', 'teddy'],
                "age": [24,26,25],
                "city": ['agra', "mummai", "goa"]}

In [ ]:
#panda take 2 data structures: 
#1. series - single column ( columns are called as features)
#2. dataframe - mutliple columns(series)
df = pd.DataFrame(student_data) # workspace for panda where it loads data
df["name"]

0    claude
1      jack
2     teddy
Name: name, dtype: str

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   city    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [8]:
df.dtypes

name      str
age     int64
city      str
dtype: object

In [10]:
df.shape # (rows, columns)

(3, 3)

In [11]:
df.columns

Index(['name', 'age', 'city'], dtype='str')

In [13]:
df[['name', 'age']]

     name  age
0  claude   24
1    jack   26
2   teddy   25

In [14]:
#to fetch a specific row in df loc and iloc
df.iloc[1]

name      jack
age         26
city    mummai
Name: 1, dtype: object

In [27]:
#fetching multiple rows(records)
# df.iloc[0:2] #iloc[row(+1), column(+1)]
df.iloc[0:, 1:]

   age    city
0   24    agra
1   26  mummai
2   25     goa